services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: feeder
      POSTGRES_PASSWORD: feeder
      POSTGRES_DB: feeder_site
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: feeder
      RABBITMQ_DEFAULT_PASS: feeder

volumes:
  postgres_data:
